cc_library(
    name = "netlink_backend",
    srcs = ["*.cpp"],
    hdrs = ["*.h" ],
)


cc_library(
    name = "netlink_socket",
    srcs = ["netlink_socket.cpp"],
    hdrs = ["netlink_socket.h" ],
)