package(default_visibility = ["//visibility:public"])
# cc_library(
#     name = "netlink_backend",
#     srcs = ["*.cpp"],
#     hdrs = ["*.h" ],
# )


cc_library(
    name = "netlink_socket",
    srcs = ["netlink_socket.cpp"],
    hdrs = ["netlink_socket.h" ],
    deps = ["//backend/request:nl_request"]
)