# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
  name = "main_app",
  srcs = ["main/main_app.cpp"],
  deps = ["//helpers:helper_hdrs",
    "//helpers:helper_iface_hdrs",
    "//helpers:helper",
  ],
)