# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "rule unique name",
    srcs = ["source files"],
    copts = [],
    deps = ["libraries to be linked"],
)


# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
    name = "rule unique name",
    srcs = ["source files"],
    hdrs = ["header files"],
    deps = ["header files"],
)


cc_test(
    
)