# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "wake_me",
    srcs = ["wake_me.cpp"],
    # copts = ["-pthread"],
    # deps = ["pthread"],
    linkopts = ["-lpthread"]
)