# new_local_repository(
#   name = "boost",
#   build_file = "boost.BUILD",
#   path = "/usr/lib64"
#  )

# https://docs.bazel.build/versions/master/be/workspace.html#new_http_archive
new_http_archive(
  name = "boost",	# Reference as @boost//:target-lib
  build_file = "boost.BUILD",
  sha256 = "da3411ea45622579d419bfda66f45cd0f8c32a181d84adfa936f5688388995cf", # version 1.68
  urls = ["https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz"],
  strip_prefix = ""
)