# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
package(default_visibility = ["//visibility:public"])
cc_library(
    name = "nl_request",
    srcs = ["nl_request.cpp"],
    hdrs = ["nl_request.h"],
    # strip_include_prefix= "backend"
)