# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "serial_producer",
    srcs = ["prod/serial_prod.cpp"],
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "serial_consumer",
    srcs = ["cons/serial_consumer.cpp"],
)

# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "serialize",
    srcs = ["serialize.cpp"],
)

# https://olegkutkov.me/2018/02/14/monitoring-linux-networking-state-using-netlink/