cc_binary(
    name = "netcfg",
    srcs = ["netcfg.cpp", "netcfg.hpp"],
    deps = [
        "//backend:netlink_socket", 
        "//backend/request:nl_request",
        "//backend:nlmsg",
    ]
)


