load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "googletest",
    # build_file = "@//:gmock.BUILD",
    # build_file = "@google//BUILD.bazel",
    remote = "https://github.com/google/googletest",
    tag = "release-1.8.1",
)
